---
name: 'Mojisoluwa (Jiso) Awe'
title: "R Notebook"
output: html_notebook
---

# What is PCT?

In Major League Baseball Pct is the statistic for winning percentage, typically the third stat presented in data about standings (displayed as a decimal). The higher this percentage, the higher the ratio is between a teams wins and losses. This statistic is the primary component examined in team rankings.

The highest Pct. in MLB history was 0.716 from the 2001 Seattle Mariners. In baseball any Pct. above 0.500 is a very big accomplishment.

* despite this amazing season by the Mariners, they haven't been as lucky any other season and are still the only MLB team to not have a single World Series appearance


## Calculation

### Win Percentage is calculated based on two variables: wins and losses.


$$\frac{Wins}{Wins+Losses}$$

* note: Wins + Losses can also be referred to as Games Played (GP)

# Visualization

This section will be dedicated to visualizations based on different teams winning percentages in different seasons.
