---
name: 'Mojisoluwa (Jiso) Awe' 
title: "Post Season Visualizations"
output: html_notebook
---

# The Post Season

During every MLB season the question of which teams are making it to the post season are frequent topics of debate.




```{r}
library(tidyverse)     ##loading packages
library(ggplot2)
library(dcData)
library(rvest)
library(dplyr)
library(ggplot2)
library(lubridate)
```

```{r}
install.packages('editData')
```


```{r}
page538 <- 'https://projects.fivethirtyeight.com/2021-mlb-predictions/'
table <- page538 %>%
  read_html() %>%
  html_nodes(css = 'table') %>%
  html_table(fill = TRUE)

table
```


```{r}
table2 <-
  data.frame(table[[1]])

table2
```


```{r}
table3 <-
  subset(table2, select = c(1,2,3,7,9))

table3
```


```{r}
table4 <-
  table3 %>%
  filter(row_number() > 2) %>%
  rename(  Team = 1,
           Division = 2,
           Rating = 3,
           Playoff = 4,
           WSWin = 5)

table4
```
```{r}
require(editData)
ftable <- editData(table4)
 ##renamed the teams using the editData package
```
```{r}
final <- editData(ftable)
```
```{r}
final
```


```{r}
library(esquisse)
```


```{r}
esquisser()
```









